2025-02-25 11:14:25,651 INFO    MainThread:143636 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 11:14:25,651 INFO    MainThread:143636 [wandb_setup.py:_flush():67] Configure stats pid to 143636
2025-02-25 11:14:25,651 INFO    MainThread:143636 [wandb_setup.py:_flush():67] Loading settings from /gpfs/users/islamm/.config/wandb/settings
2025-02-25 11:14:25,651 INFO    MainThread:143636 [wandb_setup.py:_flush():67] Loading settings from /gpfs/workdir/islamm/wandb_draw/wandb/settings
2025-02-25 11:14:25,651 INFO    MainThread:143636 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /gpfs/workdir/islamm/wandb_draw/wandb/run-20250225_111425-kehzepdx/logs/debug.log
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /gpfs/workdir/islamm/wandb_draw/wandb/run-20250225_111425-kehzepdx/logs/debug-internal.log
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:init():761] calling init triggers
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:init():784] starting backend
2025-02-25 11:14:25,652 INFO    MainThread:143636 [wandb_init.py:init():788] sending inform_init request
2025-02-25 11:14:26,012 INFO    MainThread:143636 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-25 11:14:26,013 INFO    MainThread:143636 [wandb_init.py:init():803] backend started and connected
2025-02-25 11:14:26,017 INFO    MainThread:143636 [wandb_init.py:init():896] updated telemetry
2025-02-25 11:14:26,185 INFO    MainThread:143636 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-25 11:14:26,438 INFO    MainThread:143636 [wandb_init.py:init():995] starting run threads in backend
2025-02-25 11:14:53,111 INFO    MainThread:143636 [wandb_run.py:_console_start():2377] atexit reg
2025-02-25 11:14:53,113 INFO    MainThread:143636 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-25 11:14:53,115 INFO    MainThread:143636 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-25 11:14:53,115 INFO    MainThread:143636 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-25 11:14:54,024 INFO    MainThread:143636 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-25 11:14:54,163 WARNING MsgRouterThr:143636 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/gpfs/users/islamm/.local/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/users/islamm/.local/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/users/islamm/.local/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/users/islamm/.local/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/users/islamm/.local/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-25 11:14:54,425 INFO    MsgRouterThr:143636 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
